import { createClient } from 'npm:@supabase/supabase-js@2'
import webpush from 'npm:web-push@3.6.7'

// GENERATED by scripts/build-edge-function.mjs - do not edit; edit supabase/functions/send-notifications/ instead.
// ---- logic ----
// Pure scheduling logic for Jadwali notifications. No I/O, so it can be unit tested with Node.

type Task = {
  id: string
  user_id: string
  title: string
  due_date: string | null // YYYY-MM-DD
  due_time: string | null // HH:MM[:SS]
  status: string
  remind_before_minutes: number | null // null = "remind me before" is off
  notify_at_time: boolean | null // "notify me at task time"
  updated_at: string | null // when the task was last saved
  companies?: { name: string } | null
}

type Settings = {
  user_id: string
  timezone: string
  daily_summary_enabled: boolean
  daily_summary_time: string // HH:MM[:SS]
}

type Kind = 'reminder' | 'at_time' | 'daily_summary'

type Notification = {
  user_id: string
  task_id: string | null
  kind: Kind
  dedupe_key: string
  payload: { title: string; body: string; url: string; tag: string }
}

const DEFAULT_DUE_TIME = '09:00'
// A trigger is only sent if it fired within this window. This keeps a delayed
// cron run from sending stale alerts.
const GRACE_MS = 3 * 60 * 60 * 1000

function safeTimeZone(tz: string): string {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: tz })
    return tz
  } catch {
    return 'UTC'
  }
}

function tzOffsetMs(utcMs: number, tz: string): number {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: tz,
    hourCycle: 'h23',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  }).formatToParts(new Date(utcMs))
  const get = (t: string) => Number(parts.find(p => p.type === t)!.value)
  const asUtc = Date.UTC(get('year'), get('month') - 1, get('day'), get('hour'), get('minute'), get('second'))
  return asUtc - Math.floor(utcMs / 1000) * 1000
}

/** Converts a wall-clock date + time in `tz` to a UTC epoch (ms). */
function zonedTimeToUtcMs(dateStr: string, timeStr: string, tz: string): number {
  const zone = safeTimeZone(tz)
  const [y, m, d] = dateStr.split('-').map(Number)
  const [hh, mm] = timeStr.split(':').map(Number)
  const guess = Date.UTC(y, m - 1, d, hh, mm)
  const off1 = tzOffsetMs(guess, zone)
  let t = guess - off1
  const off2 = tzOffsetMs(t, zone)
  if (off2 !== off1) t = guess - off2
  return t
}

/** The wall-clock date (YYYY-MM-DD) and time (HH:MM) of `nowMs` in `tz`. */
function localParts(nowMs: number, tz: string): { date: string; time: string } {
  const zone = safeTimeZone(tz)
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: zone,
    hourCycle: 'h23',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  }).formatToParts(new Date(nowMs))
  const get = (t: string) => parts.find(p => p.type === t)!.value
  return { date: `${get('year')}-${get('month')}-${get('day')}`, time: `${get('hour')}:${get('minute')}` }
}

function addDays(dateStr: string, days: number): string {
  const [y, m, d] = dateStr.split('-').map(Number)
  const dt = new Date(Date.UTC(y, m - 1, d + days))
  return dt.toISOString().slice(0, 10)
}

function formatTime12(timeStr: string): string {
  const [h, m] = timeStr.split(':').map(Number)
  return `${h % 12 || 12}:${String(m).padStart(2, '0')} ${h >= 12 ? 'PM' : 'AM'}`
}

function formatDateShort(dateStr: string): string {
  const [y, m, d] = dateStr.split('-').map(Number)
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString('en-US', {
    weekday: 'short', month: 'short', day: 'numeric', timeZone: 'UTC',
  })
}

function relativeDay(dateStr: string, today: string): string {
  if (dateStr === today) return 'today'
  if (dateStr === addDays(today, 1)) return 'tomorrow'
  return formatDateShort(dateStr)
}

const hhmm = (t: string) => t.slice(0, 5)

function suffix(task: Task): string {
  return task.companies?.name ? ` · ${task.companies.name}` : ''
}

/** "15 min", "1 hour", "2 hours", "1 day" */
function formatLead(minutes: number): string {
  if (minutes % 1440 === 0) return minutes === 1440 ? '1 day' : `${minutes / 1440} days`
  if (minutes % 60 === 0) return minutes === 60 ? '1 hour' : `${minutes / 60} hours`
  return `${minutes} min`
}

/**
 * Decides which per-task notifications should be sent right now:
 *  - "reminder": `remind_before_minutes` before the task's date/time (null = off)
 *  - "at_time":  exactly at the task's date/time (`notify_at_time`)
 * The two are independent. A task with a date but no time counts as 09:00. A notification is skipped
 * if its moment had already passed when the task was last saved (no late "reminders" for the past).
 * Returns candidates only; the caller de-duplicates via the log.
 */
function buildTaskNotifications(nowMs: number, tasks: Task[], settingsByUser: Map<string, Settings>): Notification[] {
  const out: Notification[] = []

  for (const task of tasks) {
    const settings = settingsByUser.get(task.user_id)
    if (!settings || !task.due_date || task.status === 'done') continue

    const tz = settings.timezone
    const dueTime = hhmm(task.due_time || DEFAULT_DUE_TIME)
    const dueMs = zonedTimeToUtcMs(task.due_date, dueTime, tz)
    const savedMs = task.updated_at ? Date.parse(task.updated_at) : 0
    const today = localParts(nowMs, tz).date
    const baseKey = `${task.id}|${task.due_date}|${task.due_time || ''}`
    const url = '/tasks'
    const isDue = (triggerMs: number) => nowMs >= triggerMs && nowMs < triggerMs + GRACE_MS && triggerMs >= savedMs

    // 1) Reminder before the task
    const lead = task.remind_before_minutes
    if (lead && lead > 0 && isDue(dueMs - lead * 60_000)) {
      out.push({
        user_id: task.user_id,
        task_id: task.id,
        kind: 'reminder',
        dedupe_key: `${baseKey}|before|${lead}`,
        payload: {
          title: `Reminder: ${task.title}`,
          body: `In ${formatLead(lead)} · ${relativeDay(task.due_date, today)} at ${formatTime12(dueTime)}${suffix(task)}`,
          url,
          tag: `${task.id}-reminder`,
        },
      })
    }

    // 2) Notify at the task's time
    if (task.notify_at_time && isDue(dueMs)) {
      out.push({
        user_id: task.user_id,
        task_id: task.id,
        kind: 'at_time',
        dedupe_key: `${baseKey}|at`,
        payload: {
          title: `Now: ${task.title}`,
          body: `Scheduled for ${formatTime12(dueTime)}${suffix(task)}`,
          url,
          tag: `${task.id}-at-time`,
        },
      })
    }
  }

  return out
}

/** True when this user's daily summary should be considered right now. */
function summaryLocalDateIfDue(nowMs: number, settings: Settings): string | null {
  if (!settings.daily_summary_enabled) return null
  const tz = settings.timezone
  const { date } = localParts(nowMs, tz)
  const triggerMs = zonedTimeToUtcMs(date, hhmm(settings.daily_summary_time), tz)
  return nowMs >= triggerMs && nowMs < triggerMs + GRACE_MS ? date : null
}

type SummaryTask = { title: string; due_time: string | null; priority: string | null }

const SUMMARY_MAX_TITLES = 8
const SUMMARY_MAX_CHARS = 170 // lock screens show only a few lines
const PRIORITY_RANK: Record<string, number> = { high: 0, medium: 1, low: 2 }

function clip(text: string, max: number): string {
  return text.length > max ? text.slice(0, max - 1).trimEnd() + '…' : text
}

/** Today's tasks in the order you'd do them: timed ones by time first, then by priority. */
function sortSummaryTasks(tasks: SummaryTask[]): SummaryTask[] {
  return [...tasks].sort((a, b) => {
    if (!!a.due_time !== !!b.due_time) return a.due_time ? -1 : 1
    if (a.due_time && b.due_time && a.due_time !== b.due_time) return a.due_time < b.due_time ? -1 : 1
    const pa = PRIORITY_RANK[a.priority || ''] ?? 1
    const pb = PRIORITY_RANK[b.priority || ''] ?? 1
    return pa !== pb ? pa - pb : a.title.localeCompare(b.title)
  })
}

/** "Good morning, are you ready?" + today's task titles ("task1, task2, +N more"). Null when nothing is due. */
function buildSummaryNotification(userId: string, localDate: string, todaysTasks: SummaryTask[]): Notification | null {
  if (todaysTasks.length === 0) return null
  const titles = sortSummaryTasks(todaysTasks).map(t => clip(t.title.trim(), 60))
  const shown: string[] = []
  for (const t of titles) {
    const next = [...shown, t].join(', ')
    if (shown.length > 0 && (shown.length >= SUMMARY_MAX_TITLES || next.length > SUMMARY_MAX_CHARS)) break
    shown.push(t)
  }
  const more = titles.length - shown.length
  return {
    user_id: userId,
    task_id: null,
    kind: 'daily_summary',
    dedupe_key: localDate,
    payload: {
      title: 'Good morning, are you ready?',
      body: shown.join(', ') + (more > 0 ? `, +${more} more` : ''),
      url: '/dashboard',
      tag: 'daily-summary',
    },
  }
}

// ---- orchestration ----
// Orchestrates one scheduler tick. All I/O goes through the `Deps` interface so the
// flow (dedupe, retry, dead-subscription pruning) can be tested with in-memory fakes.

type Subscription = { id: string; user_id: string; endpoint: string; p256dh: string; auth: string }

type Deps = {
  listSubscriptions(): Promise<Subscription[]>
  listSettings(userIds: string[]): Promise<Settings[]>
  listTasks(userIds: string[], dateFrom: string, dateTo: string): Promise<Task[]>
  /** Tasks due on `localToday` that are not done. */
  todaysTasks(userId: string, localToday: string): Promise<SummaryTask[]>
  summarySent(userId: string, localDate: string): Promise<boolean>
  /** Inserts log rows; returns ONLY the rows that were newly inserted (unique key prevents duplicates). */
  insertLog(rows: Notification[]): Promise<Notification[]>
  deleteLog(rows: Notification[]): Promise<void>
  deleteSubscription(id: string): Promise<void>
  /** Throws an error with `statusCode` on failure (404/410 = subscription is gone). */
  send(sub: Subscription, payload: Notification['payload']): Promise<void>
}

type TickResult = { candidates: number; sent: number; duplicates: number; failed: number; pruned: number }

async function deliver(deps: Deps, subs: Subscription[], payload: Notification['payload']) {
  let ok = 0
  let failed = 0
  let pruned = 0
  for (const sub of subs) {
    try {
      await deps.send(sub, payload)
      ok++
    } catch (err) {
      const status = (err as { statusCode?: number }).statusCode
      if (status === 404 || status === 410) {
        await deps.deleteSubscription(sub.id)
        pruned++
      } else {
        failed++
      }
    }
  }
  return { ok, failed, pruned }
}

async function runTick(deps: Deps, nowMs: number): Promise<TickResult> {
  const result: TickResult = { candidates: 0, sent: 0, duplicates: 0, failed: 0, pruned: 0 }

  const subs = await deps.listSubscriptions()
  if (subs.length === 0) return result

  const subsByUser = new Map<string, Subscription[]>()
  for (const s of subs) subsByUser.set(s.user_id, [...(subsByUser.get(s.user_id) || []), s])
  const userIds = [...subsByUser.keys()]

  const settingsByUser = new Map((await deps.listSettings(userIds)).map(s => [s.user_id, s]))

  // Wide enough to cover every timezone and the "1 day before" reminder.
  const utcToday = new Date(nowMs).toISOString().slice(0, 10)
  const tasks = await deps.listTasks(userIds, addDays(utcToday, -2), addDays(utcToday, 3))

  const candidates = buildTaskNotifications(nowMs, tasks, settingsByUser)

  for (const settings of settingsByUser.values()) {
    const date = summaryLocalDateIfDue(nowMs, settings)
    if (!date || (await deps.summarySent(settings.user_id, date))) continue
    const todays = await deps.todaysTasks(settings.user_id, localParts(nowMs, settings.timezone).date)
    const n = buildSummaryNotification(settings.user_id, date, todays)
    if (n) candidates.push(n)
  }

  result.candidates = candidates.length
  if (candidates.length === 0) return result

  const fresh = await deps.insertLog(candidates)
  result.duplicates = candidates.length - fresh.length

  for (const n of fresh) {
    const userSubs = subsByUser.get(n.user_id) || []
    const { ok, failed, pruned } = await deliver(deps, userSubs, n.payload)
    result.failed += failed
    result.pruned += pruned
    if (ok > 0) {
      result.sent++
    } else if (failed > 0) {
      // Nothing was delivered because of a transient error: free the dedupe slot so the next tick retries.
      await deps.deleteLog([n])
    }
  }

  return result
}

/** Sends a test push to every device of one user (no dedupe, no log). */
async function sendTest(deps: Deps, userId: string, subs: Subscription[]) {
  return deliver(deps, subs.filter(s => s.user_id === userId), {
    title: 'Jadwali notifications are on',
    body: 'This is a test notification. You will get reminders here.',
    url: '/profile',
    tag: 'test',
  })
}

// ---- entry point ----

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-cron-secret',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

function safeEqual(a: string, b: string) {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return diff === 0
}

const admin = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!, {
  auth: { persistSession: false, autoRefreshToken: false },
})

let vapidReady = false
function ensureVapid() {
  if (vapidReady) return
  const subject = Deno.env.get('VAPID_SUBJECT')
  const pub = Deno.env.get('VAPID_PUBLIC_KEY')
  const priv = Deno.env.get('VAPID_PRIVATE_KEY')
  if (!subject || !pub || !priv) throw new Error('VAPID_SUBJECT, VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY secrets are not set')
  webpush.setVapidDetails(subject, pub, priv)
  vapidReady = true
}

const logKey = (n: Pick<Notification, 'user_id' | 'kind' | 'dedupe_key'>) => `${n.user_id}|${n.kind}|${n.dedupe_key}`

const deps: Deps = {
  async listSubscriptions() {
    const { data, error } = await admin.from('push_subscriptions').select('id,user_id,endpoint,p256dh,auth')
    if (error) throw error
    return data as Subscription[]
  },
  async listSettings(userIds) {
    const { data, error } = await admin.from('notification_settings').select('*').in('user_id', userIds)
    if (error) throw error
    return data as Settings[]
  },
  async listTasks(userIds, dateFrom, dateTo) {
    const { data, error } = await admin
      .from('tasks')
      .select('id,user_id,title,due_date,due_time,status,remind_before_minutes,notify_at_time,updated_at,companies(name)')
      .in('user_id', userIds)
      .neq('status', 'done')
      .or('remind_before_minutes.not.is.null,notify_at_time.eq.true')
      .gte('due_date', dateFrom)
      .lte('due_date', dateTo)
    if (error) throw error
    return data as unknown as Task[]
  },
  async todaysTasks(userId, localToday) {
    const { data, error } = await admin
      .from('tasks')
      .select('title,due_time,priority')
      .eq('user_id', userId)
      .neq('status', 'done')
      .eq('due_date', localToday)
    if (error) throw error
    return data as SummaryTask[]
  },
  async summarySent(userId, localDate) {
    const { count, error } = await admin
      .from('notification_log')
      .select('id', { count: 'exact', head: true })
      .eq('user_id', userId)
      .eq('kind', 'daily_summary')
      .eq('dedupe_key', localDate)
    if (error) throw error
    return (count ?? 0) > 0
  },
  async insertLog(rows) {
    const { data, error } = await admin
      .from('notification_log')
      .upsert(
        rows.map(r => ({ user_id: r.user_id, task_id: r.task_id, kind: r.kind, dedupe_key: r.dedupe_key })),
        { onConflict: 'user_id,kind,dedupe_key', ignoreDuplicates: true },
      )
      .select('user_id,kind,dedupe_key')
    if (error) throw error
    const inserted = new Set((data || []).map(logKey))
    return rows.filter(r => inserted.has(logKey(r)))
  },
  async deleteLog(rows) {
    for (const r of rows) {
      await admin.from('notification_log').delete().eq('user_id', r.user_id).eq('kind', r.kind).eq('dedupe_key', r.dedupe_key)
    }
  },
  async deleteSubscription(id) {
    await admin.from('push_subscriptions').delete().eq('id', id)
  },
  async send(sub, payload) {
    ensureVapid()
    await webpush.sendNotification(
      { endpoint: sub.endpoint, keys: { p256dh: sub.p256dh, auth: sub.auth } },
      JSON.stringify(payload),
      { TTL: 60 * 60, urgency: 'high' },
    )
  },
}

Deno.serve(async req => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })
  if (req.method !== 'POST') return json({ error: 'method not allowed' }, 405)

  try {
    // Cron path
    const secret = req.headers.get('x-cron-secret')
    if (secret) {
      const { data: row } = await admin.from('app_private').select('value').eq('key', 'cron_secret').maybeSingle()
      if (row?.value && safeEqual(secret, row.value)) {
        return json(await runTick(deps, Date.now()))
      }
    }

    // Signed-in user test path
    const jwt = (req.headers.get('authorization') || '').replace(/^Bearer\s+/i, '')
    const body = await req.json().catch(() => ({}))
    if (jwt && body?.action === 'test') {
      const { data, error } = await admin.auth.getUser(jwt)
      if (error || !data.user) return json({ error: 'unauthorized' }, 401)
      const { data: subs, error: subsError } = await admin
        .from('push_subscriptions')
        .select('id,user_id,endpoint,p256dh,auth')
        .eq('user_id', data.user.id)
      if (subsError) throw subsError
      if (!subs?.length) return json({ error: 'no devices registered' }, 404)
      const res = await sendTest(deps, data.user.id, subs as Subscription[])
      return json(res)
    }

    return json({ error: 'unauthorized' }, 401)
  } catch (err) {
    console.error('send-notifications failed', err)
    return json({ error: String((err as Error).message || err) }, 500)
  }
})
